# ========================= SAMPLE DATA ========================= #
# This file contains sample data for RFPs, OEM products, test pricing, and volume discounts.

# Sample RFP Database (simulating web scraping results)
SAMPLE_RFPS = [
    {
        "id": "RFP-2026-001",
        "title": "Power Cables Supply for Metro Rail Project Phase-II",
        "client": "Delhi Metro Rail Corporation (DMRC)",
        "submission_deadline": "2026-03-15",
        "estimated_value": "₹4.5 Cr",
        "url": "https://dmrc.delhi.gov.in/tenders/RFP-2026-001",
        "scope_of_supply": [
            {"item": "1.1 kV XLPE Power Cable - 3C x 120 sqmm", "quantity": "5000 m"},
            {"item": "1.1 kV XLPE Power Cable - 3C x 240 sqmm", "quantity": "3000 m"},
            {"item": "Control Cable 16 Core - 1.5 sqmm", "quantity": "8000 m"},
            {"item": "Control Cable 24 Core - 1.5 sqmm", "quantity": "4000 m"},
            {"item": "Fire Retardant Cable FR-LSH 4C x 6 sqmm", "quantity": "2000 m"},
        ],
        "technical_specs": {
            "voltage_grade": "1.1 kV",
            "insulation": "XLPE",
            "conductor": "Copper, Class 2 stranded",
            "standards": ["IS 7098 Part 1", "IEC 60502-1"],
            "temperature_rating": "90°C continuous, 250°C short circuit",
        },
        "testing_requirements": [
            "Type Test as per IS 7098",
            "Factory Acceptance Test (FAT)",
            "Site Acceptance Test (SAT)",
            "Partial Discharge Test",
            "High Voltage Test",
        ],
    },
    {
        "id": "RFP-2026-002",
        "title": "Electrical Cables for Smart City Infrastructure",
        "client": "Pune Smart City Development Corporation",
        "submission_deadline": "2026-04-20",
        "estimated_value": "₹2.8 Cr",
        "url": "https://punesmartcity.in/tenders/RFP-2026-002",
        "scope_of_supply": [
            {"item": "LT XLPE Cable 3.5C x 95 sqmm", "quantity": "6000 m"},
            {"item": "Armoured Cable 4C x 16 sqmm", "quantity": "10000 m"},
            {"item": "Instrumentation Cable 2 Pair x 1.5 sqmm", "quantity": "5000 m"},
        ],
        "technical_specs": {
            "voltage_grade": "1.1 kV",
            "insulation": "XLPE",
            "armour": "Galvanized Steel Wire/Strip",
            "standards": ["IS 7098 Part 1", "IS 1554 Part 1"],
        },
        "testing_requirements": [
            "Routine Test",
            "Type Test",
            "Factory Acceptance Test (FAT)",
        ],
    },
    {
        "id": "RFP-2026-003",
        "title": "Industrial Wiring for Manufacturing Plant",
        "client": "Tata Steel Limited",
        "submission_deadline": "2026-02-28",
        "estimated_value": "₹1.2 Cr",
        "url": "https://tatasteel.com/procurement/RFP-2026-003",
        "scope_of_supply": [
            {"item": "Flexible Cable 4C x 4 sqmm", "quantity": "3000 m"},
            {"item": "Welding Cable 70 sqmm", "quantity": "1000 m"},
            {"item": "Earthing Cable 1C x 50 sqmm", "quantity": "2000 m"},
        ],
        "technical_specs": {
            "voltage_grade": "450/750 V",
            "insulation": "PVC/Rubber",
            "conductor": "Copper, flexible",
            "standards": ["IS 694", "IS 9968"],
        },
        "testing_requirements": [
            "Routine Test",
            "Sample Test",
        ],
    },
]

# OEM Product Catalog (simulating product datasheets)
OEM_PRODUCT_CATALOG = [
    {
        "sku": "PWR-XLPE-3C120-1.1",
        "name": "XLPE Power Cable 1.1kV 3C x 120 sqmm",
        "category": "Power Cable",
        "specs": {
            "voltage_grade": "1.1 kV",
            "cores": 3,
            "conductor_size_sqmm": 120,
            "insulation": "XLPE",
            "conductor_material": "Copper",
            "conductor_class": "Class 2 stranded",
            "temperature_rating": "90°C",
            "standards": ["IS 7098 Part 1", "IEC 60502-1"],
        },
        "base_price_per_meter": 485,
    },
    {
        "sku": "PWR-XLPE-3C240-1.1",
        "name": "XLPE Power Cable 1.1kV 3C x 240 sqmm",
        "category": "Power Cable",
        "specs": {
            "voltage_grade": "1.1 kV",
            "cores": 3,
            "conductor_size_sqmm": 240,
            "insulation": "XLPE",
            "conductor_material": "Copper",
            "conductor_class": "Class 2 stranded",
            "temperature_rating": "90°C",
            "standards": ["IS 7098 Part 1", "IEC 60502-1"],
        },
        "base_price_per_meter": 890,
    },
    {
        "sku": "PWR-XLPE-3C150-1.1",
        "name": "XLPE Power Cable 1.1kV 3C x 150 sqmm",
        "category": "Power Cable",
        "specs": {
            "voltage_grade": "1.1 kV",
            "cores": 3,
            "conductor_size_sqmm": 150,
            "insulation": "XLPE",
            "conductor_material": "Copper",
            "conductor_class": "Class 2 stranded",
            "temperature_rating": "90°C",
            "standards": ["IS 7098 Part 1"],
        },
        "base_price_per_meter": 580,
    },
    {
        "sku": "CTL-16C-1.5",
        "name": "Control Cable 16 Core 1.5 sqmm",
        "category": "Control Cable",
        "specs": {
            "voltage_grade": "1.1 kV",
            "cores": 16,
            "conductor_size_sqmm": 1.5,
            "insulation": "PVC",
            "conductor_material": "Copper",
            "shielded": False,
            "standards": ["IS 1554 Part 1"],
        },
        "base_price_per_meter": 320,
    },
    {
        "sku": "CTL-24C-1.5",
        "name": "Control Cable 24 Core 1.5 sqmm",
        "category": "Control Cable",
        "specs": {
            "voltage_grade": "1.1 kV",
            "cores": 24,
            "conductor_size_sqmm": 1.5,
            "insulation": "PVC",
            "conductor_material": "Copper",
            "shielded": False,
            "standards": ["IS 1554 Part 1"],
        },
        "base_price_per_meter": 445,
    },
    {
        "sku": "CTL-12C-1.5",
        "name": "Control Cable 12 Core 1.5 sqmm",
        "category": "Control Cable",
        "specs": {
            "voltage_grade": "1.1 kV",
            "cores": 12,
            "conductor_size_sqmm": 1.5,
            "insulation": "PVC",
            "conductor_material": "Copper",
            "standards": ["IS 1554 Part 1"],
        },
        "base_price_per_meter": 280,
    },
    {
        "sku": "FR-LSH-4C6",
        "name": "Fire Retardant FR-LSH Cable 4C x 6 sqmm",
        "category": "Fire Retardant Cable",
        "specs": {
            "voltage_grade": "1.1 kV",
            "cores": 4,
            "conductor_size_sqmm": 6,
            "insulation": "FR-LSH (Low Smoke Halogen Free)",
            "conductor_material": "Copper",
            "fire_rating": "IEC 60332-3",
            "standards": ["IS 7098 Part 2", "IEC 60332"],
        },
        "base_price_per_meter": 195,
    },
    {
        "sku": "FR-LSH-4C4",
        "name": "Fire Retardant FR-LSH Cable 4C x 4 sqmm",
        "category": "Fire Retardant Cable",
        "specs": {
            "voltage_grade": "1.1 kV",
            "cores": 4,
            "conductor_size_sqmm": 4,
            "insulation": "FR-LSH",
            "conductor_material": "Copper",
            "standards": ["IS 7098 Part 2"],
        },
        "base_price_per_meter": 165,
    },
    {
        "sku": "LT-XLPE-3.5C95",
        "name": "LT XLPE Cable 3.5C x 95 sqmm",
        "category": "Power Cable",
        "specs": {
            "voltage_grade": "1.1 kV",
            "cores": 3.5,
            "conductor_size_sqmm": 95,
            "insulation": "XLPE",
            "conductor_material": "Copper",
            "standards": ["IS 7098 Part 1"],
        },
        "base_price_per_meter": 420,
    },
    {
        "sku": "ARM-4C16",
        "name": "Armoured Cable 4C x 16 sqmm",
        "category": "Armoured Cable",
        "specs": {
            "voltage_grade": "1.1 kV",
            "cores": 4,
            "conductor_size_sqmm": 16,
            "insulation": "XLPE",
            "armour": "Galvanized Steel Wire",
            "conductor_material": "Copper",
            "standards": ["IS 7098 Part 1", "IS 1554 Part 1"],
        },
        "base_price_per_meter": 285,
    },
    {
        "sku": "INST-2P1.5",
        "name": "Instrumentation Cable 2 Pair x 1.5 sqmm",
        "category": "Instrumentation Cable",
        "specs": {
            "voltage_grade": "300/500 V",
            "pairs": 2,
            "conductor_size_sqmm": 1.5,
            "insulation": "PE/PVC",
            "shielded": True,
            "conductor_material": "Copper",
            "standards": ["IS 1554 Part 1"],
        },
        "base_price_per_meter": 125,
    },
    {
        "sku": "FLEX-4C4",
        "name": "Flexible Cable 4C x 4 sqmm",
        "category": "Flexible Cable",
        "specs": {
            "voltage_grade": "450/750 V",
            "cores": 4,
            "conductor_size_sqmm": 4,
            "insulation": "PVC",
            "conductor_material": "Copper",
            "conductor_class": "Class 5 flexible",
            "standards": ["IS 694"],
        },
        "base_price_per_meter": 95,
    },
    {
        "sku": "WELD-70",
        "name": "Welding Cable 70 sqmm",
        "category": "Welding Cable",
        "specs": {
            "voltage_grade": "450/750 V",
            "conductor_size_sqmm": 70,
            "insulation": "Rubber",
            "conductor_material": "Copper",
            "conductor_class": "Class 5 flexible",
            "standards": ["IS 9968 Part 1"],
        },
        "base_price_per_meter": 380,
    },
    {
        "sku": "EARTH-1C50",
        "name": "Earthing Cable 1C x 50 sqmm",
        "category": "Earthing Cable",
        "specs": {
            "cores": 1,
            "conductor_size_sqmm": 50,
            "insulation": "PVC",
            "conductor_material": "Copper",
            "color": "Green/Yellow",
            "standards": ["IS 694"],
        },
        "base_price_per_meter": 210,
    },
]

# Test Pricing Data
TEST_PRICING = {
    "Type Test as per IS 7098": {"price": 150000, "duration_days": 15},
    "Type Test": {"price": 120000, "duration_days": 12},
    "Factory Acceptance Test (FAT)": {"price": 75000, "duration_days": 5},
    "Site Acceptance Test (SAT)": {"price": 95000, "duration_days": 7},
    "Partial Discharge Test": {"price": 45000, "duration_days": 3},
    "High Voltage Test": {"price": 35000, "duration_days": 2},
    "Routine Test": {"price": 25000, "duration_days": 2},
    "Sample Test": {"price": 30000, "duration_days": 3},
}

# Volume Discount Tiers
VOLUME_DISCOUNTS = [
    {"min_quantity": 10000, "discount_percent": 8},
    {"min_quantity": 5000, "discount_percent": 5},
    {"min_quantity": 2000, "discount_percent": 3},
    {"min_quantity": 0, "discount_percent": 0},
]
